In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.preprocessing import StandardScaler, OneHotEncoder, OrdinalEncoder
from sklearn.compose import ColumnTransformer
from sklearn.model_selection import cross_val_score, KFold
from sklearn.pipeline import Pipeline

C:\Users\moham\AppData\Roaming\Python\Python310\site-packages\pandas\core\arrays\masked.py:61: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.5' currently installed).
  from pandas.core import (

In [2]:
df = pd.read_csv('feature_selection_data_1.csv')

In [3]:
df.head()

,Unnamed: 0,index,brand,ultra_hd,full_hd,Price,Rating,inches,display_type,wifi,...,Company_flipkart,ppi,resolution_width,resolution_height,fast_charging,ram,Spec_Score,size_category,charging_category,brand_category
0,0,1,tcl,1,0,10.668955,4.65,55.0,qled,1,...,1.0,3.0,1.0,2.0,1.0,1.0,3.0,1.0,2.0,big
1,1,2,lg,1,0,10.645425,4.55,55.0,led,1,...,1.0,3.0,1.0,2.0,1.0,1.0,2.0,1.0,2.0,big
2,2,3,xiaomi,1,0,10.518673,4.35,55.0,qled,1,...,0.0,3.0,1.0,2.0,2.0,1.0,2.0,1.0,1.0,big
3,3,4,lg,1,0,10.341742,4.40,43.0,led,1,...,1.0,4.0,1.0,2.0,1.0,1.0,2.0,0.0,2.0,big
4,4,5,philips,1,0,11.225243,4.05,75.0,qled,1,...,0.0,1.0,1.0,2.0,2.0,1.0,4.0,1.0,2.0,big

In [4]:
df = df.drop(columns=['Unnamed: 0'])
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

In [5]:
df.head()

,index,brand,ultra_hd,full_hd,Price,Rating,inches,display_type,wifi,rom,value_score,smart_features,Company_amazon,Company_croma,Company_flipkart,ppi,resolution_width,resolution_height,fast_charging,ram,Spec_Score,size_category,charging_category,brand_category
0,1,tcl,1,0,10.668955,4.65,55.0,qled,1,16.0,0.006272,4.0,0.0,0.0,1.0,3.0,1.0,2.0,1.0,1.0,3.0,1.0,2.0,big
1,2,lg,1,0,10.645425,4.55,55.0,led,1,19.2,0.005958,3.0,0.0,0.0,1.0,3.0,1.0,2.0,1.0,1.0,2.0,1.0,2.0,big
2,3,xiaomi,1,0,10.518673,4.35,55.0,qled,1,32.0,0.006466,4.0,1.0,0.0,0.0,3.0,1.0,2.0,2.0,1.0,2.0,1.0,1.0,big
3,4,lg,1,0,10.341742,4.40,43.0,led,1,19.2,0.007381,3.0,0.0,0.0,1.0,4.0,1.0,2.0,1.0,1.0,2.0,0.0,2.0,big
4,5,philips,1,0,11.225243,4.05,75.0,qled,1,32.0,0.003618,4.0,1.0,0.0,0.0,1.0,1.0,2.0,2.0,1.0,4.0,1.0,2.0,big

In [6]:
df.duplicated().sum()

0

In [7]:
df.isnull().sum()

index                0
brand                0
ultra_hd             0
full_hd              0
Price                0
Rating               0
inches               0
display_type         0
wifi                 0
rom                  0
value_score          0
smart_features       0
Company_amazon       0
Company_croma        0
Company_flipkart     0
ppi                  0
resolution_width     0
resolution_height    0
fast_charging        0
ram                  0
Spec_Score           0
size_category        0
charging_category    0
brand_category       0
dtype: int64

In [8]:
df = df.drop(columns = ['index'])
df.head()

,brand,ultra_hd,full_hd,Price,Rating,inches,display_type,wifi,rom,value_score,smart_features,Company_amazon,Company_croma,Company_flipkart,ppi,resolution_width,resolution_height,fast_charging,ram,Spec_Score,size_category,charging_category,brand_category
0,tcl,1,0,10.668955,4.65,55.0,qled,1,16.0,0.006272,4.0,0.0,0.0,1.0,3.0,1.0,2.0,1.0,1.0,3.0,1.0,2.0,big
1,lg,1,0,10.645425,4.55,55.0,led,1,19.2,0.005958,3.0,0.0,0.0,1.0,3.0,1.0,2.0,1.0,1.0,2.0,1.0,2.0,big
2,xiaomi,1,0,10.518673,4.35,55.0,qled,1,32.0,0.006466,4.0,1.0,0.0,0.0,3.0,1.0,2.0,2.0,1.0,2.0,1.0,1.0,big
3,lg,1,0,10.341742,4.40,43.0,led,1,19.2,0.007381,3.0,0.0,0.0,1.0,4.0,1.0,2.0,1.0,1.0,2.0,0.0,2.0,big
4,philips,1,0,11.225243,4.05,75.0,qled,1,32.0,0.003618,4.0,1.0,0.0,0.0,1.0,1.0,2.0,2.0,1.0,4.0,1.0,2.0,big

In [9]:
X = df.drop(columns = ['Price'])
y = df['Price']

In [10]:
y = np.log1p(y)

# Ordinal Encoder

In [11]:
cat_cols = ['brand', 'display_type', 'brand_category']

In [12]:
preprocessing = ColumnTransformer(transformers = [
    ('scaling', StandardScaler(), ['inches', 'Spec_Score', 'ram', 'rom', 'smart_features']),
    ('ord encoding', OrdinalEncoder(handle_unknown = 'use_encoded_value', unknown_value = -1), cat_cols),
#     ('ohe encoding', OneHotEncoder(handle_unknown = 'ignore', sparse_output = False), ['brand'])
], remainder='passthrough')

In [13]:
from sklearn.linear_model import LinearRegression
from sklearn.decomposition import PCA
pipeline = Pipeline([
    ('preprocessing', preprocessing),
    ('pca', PCA()),
    ('model', LinearRegression())
])

In [14]:
kfold = KFold(n_splits=10, shuffle=True, random_state=42)
scores = cross_val_score(pipeline, X, y, cv=kfold, scoring='r2')

In [15]:
scores.mean()

0.9718821332611391

In [16]:
scores.std()

0.0036331036844015315

In [17]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [18]:
pipeline.fit(X_train, y_train)

Pipeline(steps=[('preprocessing',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('scaling', StandardScaler(),
                                                  ['inches', 'Spec_Score',
                                                   'ram', 'rom',
                                                   'smart_features']),
                                                 ('ord encoding',
                                                  OrdinalEncoder(handle_unknown='use_encoded_value',
                                                                 unknown_value=-1),
                                                  ['brand', 'display_type',
                                                   'brand_category'])])),
                ('pca', PCA()), ('model', LinearRegression())])

In [19]:
y_pred = pipeline.predict(X_test)

In [20]:
y_pred = np.expm1(y_pred)

In [21]:
from sklearn.metrics import mean_absolute_error
mean_absolute_error(np.expm1(y_test),y_pred)

0.11045387509469784

In [22]:
def scorer(model, model_name):
    output = []
    output.append(model_name)
    
    pipeline = Pipeline([
    ('preprocessing', preprocessing),
    ('model', model)
    ])
    
    kfold = KFold(n_splits=10, shuffle=True, random_state=42)
    scores = cross_val_score(pipeline, X, y, cv=kfold, scoring='r2')
    
    output.append(scores.mean())
    
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
    
    pipeline.fit(X_train, y_train)
    
    y_pred = pipeline.predict(X_test)
    
    y_pred = np.expm1(y_pred)
    
    output.append(mean_absolute_error(np.expm1(y_test),y_pred))
    
    return output

In [23]:
## lr, ridge, lasso, svr, dst, rf, gbr, abr, etr, xgb, mlp

from sklearn.linear_model import Ridge, Lasso
from sklearn.svm import SVR
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor, AdaBoostRegressor, ExtraTreesRegressor
from sklearn.neural_network import MLPRegressor
import xgboost as xgb

In [24]:
model_dict = {
    'lr_model' : LinearRegression(),
    'ridge_model' : Ridge(),
    'lasso_model' : Lasso(),
    'svr_model' : SVR(),
    'dt_model' : DecisionTreeRegressor(),
    'rf_model' : RandomForestRegressor(),
    'gbr_model' : GradientBoostingRegressor(),
    'ad_model' : AdaBoostRegressor(),
    'et_model' : ExtraTreesRegressor(),
    'mlp_model' : MLPRegressor(),
    'xg_model' : xgb.XGBRegressor()
}

In [25]:
model_output = []
for model_name,model in model_dict.items():
    model_output.append(scorer(model, model_name))

In [26]:
model_output

[['lr_model', 0.9718821332611384, 0.11045387509469883],
 ['ridge_model', 0.8845875228415286, 0.22261513866848312],
 ['lasso_model', -0.005048794105982024, 0.7073754959019931],
 ['svr_model', 0.5172654040681128, 0.48733104915350195],
 ['dt_model', 0.9843704892796327, 0.06644203387452409],
 ['rf_model', 0.992878187327795, 0.04818849608845484],
 ['gbr_model', 0.9938188761921936, 0.046589705352980834],
 ['ad_model', 0.9780871474506064, 0.10382689427016199],
 ['et_model', 0.9933968020226468, 0.047309720700636035],
 ['mlp_model', -0.9719844796683187, 0.8789311886861352],
 ['xg_model', 0.9935765328130559, 0.04481933070011662]]

In [27]:
model_df = pd.DataFrame(model_output,
                       columns = ['name', 'r2', 'mae'])

In [28]:
model_df.sort_values(['mae'])

           name        r2       mae
10     xg_model  0.993577  0.044819
6     gbr_model  0.993819  0.046590
8      et_model  0.993397  0.047310
5      rf_model  0.992878  0.048188
4      dt_model  0.984370  0.066442
7      ad_model  0.978087  0.103827
0      lr_model  0.971882  0.110454
1   ridge_model  0.884588  0.222615
3     svr_model  0.517265  0.487331
2   lasso_model -0.005049  0.707375
9     mlp_model -0.971984  0.878931

# OneHotEncoder

In [29]:
preprocessing1 = ColumnTransformer(transformers = [
    ('scaling', StandardScaler(), ['inches', 'Spec_Score', 'ram', 'rom', 'smart_features']),
    ('ord encoding', OrdinalEncoder(handle_unknown = 'use_encoded_value', unknown_value = -1), ['display_type', 'brand_category']),
    ('ohe encoding', OneHotEncoder(handle_unknown = 'ignore', sparse_output = False), ['brand'])
], remainder='passthrough')

In [30]:
from sklearn.decomposition import PCA
pipeline1 = Pipeline([
    ('preprocessing', preprocessing1),
    ('pca', PCA()),
    ('model', LinearRegression())
])

In [31]:
kfold = KFold(n_splits=10, shuffle=True, random_state=42)
scores = cross_val_score(pipeline1, X, y, cv=kfold, scoring='r2')

In [32]:
scores.mean()

0.9773679445424529

In [33]:
scores.std()

0.0037566171824634943

In [34]:
pipeline1.fit(X_train, y_train)

Pipeline(steps=[('preprocessing',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('scaling', StandardScaler(),
                                                  ['inches', 'Spec_Score',
                                                   'ram', 'rom',
                                                   'smart_features']),
                                                 ('ord encoding',
                                                  OrdinalEncoder(handle_unknown='use_encoded_value',
                                                                 unknown_value=-1),
                                                  ['display_type',
                                                   'brand_category']),
                                                 ('ohe encoding',
                                                  OneHotEncoder(handle_unknown='ignore',
                                                                sparse_output=False),
                                                  ['brand'])])),
                ('pca', PCA()), ('model', LinearRegression())])

In [35]:
y_pred = pipeline1.predict(X_test)

In [36]:
y_pred = np.expm1(y_pred)

In [37]:
mean_absolute_error(np.expm1(y_test), y_pred)

0.09901025479970331

In [38]:
def scorer(model, model_name):
    output = []
    output.append(model_name)
    
    pipeline1 = Pipeline([
    ('preprocessing', preprocessing1),
    ('model', model)
    ])
    
    kfold = KFold(n_splits=10, shuffle=True, random_state=42)
    scores = cross_val_score(pipeline1, X, y, cv=kfold, scoring='r2')
    
    output.append(scores.mean())
    
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
    
    pipeline1.fit(X_train, y_train)
    
    y_pred = pipeline1.predict(X_test)
    
    y_pred = np.expm1(y_pred)
    
    output.append(mean_absolute_error(np.expm1(y_test),y_pred))
    
    return output

In [39]:
model_dict = {
    'lr_model' : LinearRegression(),
    'ridge_model' : Ridge(),
    'lasso_model' : Lasso(),
    'svr_model' : SVR(),
    'dt_model' : DecisionTreeRegressor(),
    'rf_model' : RandomForestRegressor(),
    'gbr_model' : GradientBoostingRegressor(),
    'ad_model' : AdaBoostRegressor(),
    'et_model' : ExtraTreesRegressor(),
    'mlp_model' : MLPRegressor(),
    'xg_model' : xgb.XGBRegressor()
}

In [40]:
model_output = []
for model_name,model in model_dict.items():
    model_output.append(scorer(model, model_name))

In [41]:
model_df = pd.DataFrame(model_output,
                       columns = ['name', 'r2', 'mae'])
model_df.sort_values(['mae'])

           name        r2       mae
10     xg_model  0.993124  0.044854
5      rf_model  0.992849  0.046932
6     gbr_model  0.993749  0.047443
8      et_model  0.992857  0.048058
4      dt_model  0.986037  0.066600
0      lr_model  0.977368  0.099010
7      ad_model  0.976981  0.110511
1   ridge_model  0.946128  0.151445
3     svr_model  0.486191  0.511557
2   lasso_model -0.005049  0.707375
9     mlp_model -0.634767  0.771799

In [42]:
from sklearn.model_selection import GridSearchCV

In [43]:
param_grid = {
    'model__n_estimators': [50, 100, 150, 200],
    'model__max_depth': [None, 10, 20, 30],
    'model__max_samples': [0.1, 0.25, 0.50, 0.75],
    'model__max_features': ['sqrt', 'log2']
}

In [44]:
preprocessing2 = ColumnTransformer(transformers = [
    ('scaling', StandardScaler(), ['inches', 'Spec_Score', 'ram', 'rom', 'smart_features']),
    ('ord encoding', OrdinalEncoder(handle_unknown = 'use_encoded_value', unknown_value = -1), ['display_type', 'brand_category']),
    ('ohe encoding', OneHotEncoder(handle_unknown = 'ignore', sparse_output = False), ['brand'])
], remainder='passthrough')

In [45]:
pipeline2 = Pipeline([
    ('preprocessing', preprocessing2),
    ('model', RandomForestRegressor(random_state=42))
])

In [46]:
kfold = KFold(n_splits=10, shuffle=True, random_state=42)
search = GridSearchCV(
    pipeline2,
    param_grid,
    cv=kfold,
    scoring='r2',
    n_jobs=-1
)

In [47]:
search.fit(X, y)

GridSearchCV(cv=KFold(n_splits=10, random_state=42, shuffle=True),
             estimator=Pipeline(steps=[('preprocessing',
                                        ColumnTransformer(remainder='passthrough',
                                                          transformers=[('scaling',
                                                                         StandardScaler(),
                                                                         ['inches',
                                                                          'Spec_Score',
                                                                          'ram',
                                                                          'rom',
                                                                          'smart_features']),
                                                                        ('ord '
                                                                         'encoding',
                                                                         OrdinalEncoder(handle_unknown='use_encoded_value',
                                                                                        unknown_value=-1),
                                                                         ['display_type',
                                                                          'brand_category']),
                                                                        ('ohe '
                                                                         'encoding',
                                                                         OneHotEncoder(handle_unknown='ignore',
                                                                                       sparse_output=False),
                                                                         ['brand'])])),
                                       ('model',
                                        RandomForestRegressor(random_state=42))]),
             n_jobs=-1,
             param_grid={'model__max_depth': [None, 10, 20, 30],
                         'model__max_features': ['sqrt', 'log2'],
                         'model__max_samples': [0.1, 0.25, 0.5, 0.75],
                         'model__n_estimators': [50, 100, 150, 200]},
             scoring='r2')

# Exporting Data

In [48]:
preprocessing2 = ColumnTransformer(transformers = [
    ('scaling', StandardScaler(), ['inches', 'Spec_Score', 'ram', 'rom', 'smart_features']),
    ('ord encoding', OrdinalEncoder(handle_unknown = 'use_encoded_value', unknown_value = -1), ['display_type', 'brand_category']),
    ('ohe encoding', OneHotEncoder(handle_unknown = 'ignore', sparse_output = False), ['brand'])
], remainder='passthrough')

In [49]:
pipeline2 = Pipeline([
    ('preprocessing', preprocessing2),
    ('model', RandomForestRegressor(random_state=42))
])

In [50]:
pipeline2.fit(X, y)

Pipeline(steps=[('preprocessing',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('scaling', StandardScaler(),
                                                  ['inches', 'Spec_Score',
                                                   'ram', 'rom',
                                                   'smart_features']),
                                                 ('ord encoding',
                                                  OrdinalEncoder(handle_unknown='use_encoded_value',
                                                                 unknown_value=-1),
                                                  ['display_type',
                                                   'brand_category']),
                                                 ('ohe encoding',
                                                  OneHotEncoder(handle_unknown='ignore',
                                                                sparse_output=False),
                                                  ['brand'])])),
                ('model', RandomForestRegressor(random_state=42))])

In [51]:
import pickle

In [52]:
with open('pipeline.pkl', 'wb') as file:
    pickle.dump(pipeline2, file)

In [53]:
with open('df.pkl', 'wb') as file:
    pickle.dump(X, file)

In [54]:
X

            brand  ultra_hd  full_hd  Rating  inches display_type  wifi   rom  \
0             tcl         1        0    4.65   55.00         qled     1  16.0
1              lg         1        0    4.55   55.00          led     1  19.2
2          xiaomi         1        0    4.35   55.00         qled     1  32.0
3              lg         1        0    4.40   43.00          led     1  19.2
4         philips         1        0    4.05   75.00         qled     1  32.0
5         hisense         1        0    4.20   55.00      miniled     1  28.8
6            sony         1        0    4.50   65.00          led     1  16.0
7           croma         0        0    4.45   32.00          led     1  16.0
8          realme         1        0    4.20   55.00         qled     1  16.0
9          xiaomi         1        0    4.65   55.00      miniled     1  32.0
10        samsung         1        0    4.55   43.00      miniled     1  25.6
11         xiaomi         0        0    4.50   32.00          led     1  16.0
12            tcl         1        0    4.40   55.00      miniled     1  22.4
13        samsung         1        0    4.70   55.00      miniled     1  28.8
14         xiaomi         1        0    4.30   43.00         qled     1  32.0
15         realme         1        0    4.25   43.00         qled     1  16.0
16            tcl         1        0    4.45   65.00      miniled     1  44.8
17        hisense         1        0    4.20   43.00         qled     1  16.0
18            tcl         0        1    4.65   32.00          led     1  16.0
19        samsung         1        0    4.30   43.00          led     1  19.2
20          lumio         1        0    4.70   55.00      miniled     1  44.8
21       motorola         1        0    4.05   43.00         qled     1  32.0
22         compaq         1        0    4.05   43.00          led     1  19.2
23           sony         1        0    4.30   65.00          lcd     1  32.0
24            tcl         1        0    4.20   55.00         qled     1  32.0
25         xiaomi         1        0    4.45   43.00      miniled     1  32.0
26        hisense         1        0    4.65   55.00         qled     1  19.2
27          lumio         1        0    4.00   43.00         qled     1  44.8
28          croma         0        0    4.35   32.00         qled     1  16.0
29       motorola         0        0    4.55   32.00         qled     1  16.0
30        hisense         1        0    4.75   50.00         qled     1  28.8
31            tcl         1        0    4.00   55.00      miniled     1  16.0
32          lumio         1        0    4.55   55.00         qled     1  44.8
33            tcl         1        0    4.05   43.00         qled     1  16.0
34             lg         1        0    4.25   43.00      miniled     1  22.4
35        samsung         1        0    4.30   50.00          led     1  19.2
36         realme         0        0    4.65   32.00         qled     1  16.0
37             vw         0        1    4.55   43.00         qled     1  19.2
38        hisense         1        0    4.20   55.00      miniled     1  28.8
39        hisense         1        0    4.25   65.00      miniled     1  32.0
40            tcl         1        0    4.45   65.00         qled     1  32.0
41        samsung         1        0    4.65   43.00      miniled     1  25.6
42             lg         1        0    4.45   43.00          led     1  19.2
43             lg         1        0    4.55   43.00          led     1  22.4
44            tcl         1        0    4.40   75.00         qled     1  32.0
45            tcl         1        0    4.45   55.00         qled     1  32.0
46            tcl         1        0    4.70   55.00         qled     1  32.0
47         xiaomi         1        0    4.10   43.00         qled     1  32.0
48         xiaomi         0        0    4.55   32.00         qled     1  16.0
49           acer         1        0    4.25   50.00         qled     1  19.2
50            tcl         0        1    4.75   32.00         qled     1  19.2
51             lg         1        0    4.75   75.00          led     1  22.4
52      blaupunkt         0        0    4.75   32.00         qled     1  16.0
53      blaupunkt         0        1    4.65   40.00         qled     1  19.2
54             lg         1        0    4.15   55.00      miniled     1  25.6
55           sony         1        0    4.60   65.00          led     1  32.0
56             vw         0        0    4.50   40.00         qled     0  16.0
57           sony         1        0    4.35   55.00          lcd     1  32.0
58             vw         0        0    4.45   32.00         qled     0  16.0
59            tcl         1        0    4.05   75.00          led     1  25.6
60            tcl         1        0    4.50   77.00         qled     1  32.0
61        hisense         1        0    4.15   75.00      miniled     1  38.4
62            tcl         1        0    4.45   75.00         qled     1  32.0
63            tcl         1        0    4.35   77.00         qled     1  32.0
64        samsung         1        0    4.35   77.00        micro     1  38.4
65             vw         0        0    4.65   32.00          led     1  16.0
66        samsung         1        0    4.20   55.00         oled     1  32.0
67       acerpure         1        0    4.20   65.00         qled     1  16.0
68        samsung         1        0    4.75   55.00         qled     1  19.2
69         xiaomi         1        0    4.10   50.00          led     1  19.2
70        philips         1        0    4.10   43.00         qled     1  32.0
71             vu         1        0    4.40   43.00         qled     1  16.0
72             lg         1        0    4.75   55.00         oled     1  44.8
73        hisense         1        0    4.60   55.00         qled     1  28.8
74            tcl         1        0    4.35   55.00      miniled     1  19.2
75            tcl         1        0    4.45   43.00         qled     1  16.0
76            tcl         1        0    4.20   65.00      miniled     1  32.0
77         realme         1        0    4.50   55.00         qled     1  32.0
78            tcl         1        0    4.15   43.00         qled     1  16.0
79         xiaomi         1        0    4.20   55.00         qled     1  32.0
80            tcl         0        1    4.15   32.00         qled     1  19.2
81             lg         0        0    4.65   32.00          led     1  16.0
82         foxsky         1        0    4.15   43.00         qled     1  19.2
83         xiaomi         0        0    4.70   32.00          led     1  16.0
84            tcl         1        0    4.35   55.00         qled     1  16.0
85            tcl         1        0    4.30   65.00         qled     1  16.0
86        samsung         1        0    4.25   65.00        micro     1  35.2
87      blaupunkt         0        1    4.70   43.00         qled     1  19.2
88           sony         1        0    4.60   55.00          led     1  19.2
89       motorola         1        0    4.50   50.00         qled     1  32.0
90       motorola         1        0    4.15   75.00      miniled     1  44.8
91        samsung         1        0    4.30   65.00      miniled     1  22.4
92        samsung         1        0    4.60   55.00      miniled     1  22.4
93             lg         1        0    4.00   65.00         oled     1  44.8
94        samsung         1        0    4.35   32.00          led     1  22.4
95             vw         0        1    4.20   40.00         qled     1  19.2
96             lg         1        0    4.40   55.00          led     1  25.6
97             lg         1        0    4.40   55.00      miniled     1  32.0
98             lg         1        0    4.70   55.00      miniled     1  16.0
99         xiaomi         1        0    4.40   55.00      miniled     1  32.0
100            vw         1        0    4.40   43.00         qled     1  32.0
101      iffalcon         1        0    4.45   55.00         qled     1  19.2
102       kenstar         0        0    4.00   32.00         qled     1  16.0
103       philips         1        0    4.70   55.00      miniled     1  32.0
104            vw         0        0    4.35   32.00          led     1  16.0
105        coocaa         1        0    4.60   55.00      miniled     1  32.0
106       samsung         1        0    4.10   43.00         qled     1  19.2
107         innoq         0        0    4.60   32.00          led     0  16.0
108            vw         0        1    4.75   40.00         qled     1  19.2
109            vw         0        1    4.35   43.00          led     1  19.2
110            vw         0        0    4.70   32.00          led     1  16.0
111            vu         1        0    4.20   55.00         qled     1  16.0
112        xiaomi         0        0    4.60   32.00          led     1  16.0
113     blaupunkt         0        1    4.75   40.00         qled     1  19.2
114       hisense         1        0    4.45   65.00      miniled     1  32.0
115          sony         1        0    4.30   43.00          led     1  19.2
116          sony         1        0    4.45   55.00          led     1  16.0
117           tcl         1        0    4.00   55.00         qled     1  32.0
118       samsung         0        0    4.05   32.00          led     0  16.0
119       samsung         1        0    4.10   55.00         qled     1  25.6
120           tcl         0        1    4.55   43.00         qled     1  19.2
121       samsung         1        0    4.25   55.00      miniled     1  19.2
122       samsung         1        0    4.70   43.00          led     1  19.2
123            lg         1        0    4.75   43.00          led     1  19.2
124       toshiba         1        0    4.00   43.00         qled     1  16.0
125           tcl         1        0    4.55   43.00         qled     1  32.0
126          marq         0        1    4.50   43.00          led     1  19.2
127     panasonic         1        0    4.35   43.00          led     1  16.0
128          sony         1        0    4.05   43.00          led     1  22.4
129       samsung         0        0    4.40   32.00          led     1  16.0
130         kodak         0        1    4.25   40.00         qled     1  19.2
131            lg         1        0    4.20   43.00      miniled     1  19.2
132            lg         1        0    4.60   65.00      miniled     1  44.8
133            lg         1        0    4.75   48.00         oled     1  44.8
134            lg         1        0    4.35   77.00         oled     1  44.8
135           tcl         1        0    4.35   55.00          led     0  25.5
136           tcl         1        0    4.15   50.00         qled     1  16.0
137           tcl         1        0    4.25   65.00          led     1  16.0
138           tcl         1        0    4.20   55.00         qled     1  32.0
139           tcl         1        0    4.55   65.00         qled     1  32.0
140           tcl         1        0    4.40   55.00         qled     1  16.0
141           tcl         1        0    4.30   43.00         qled     1  16.0
142       samsung         1        0    4.55   65.00          led     1  28.8
143       samsung         1        0    4.00   55.00      miniled     1  22.4
144           tcl         1        0    4.65   55.00         qled     1  32.0
145      motorola         1        0    4.10   77.00      miniled     1  44.8
146        realme         0        1    4.45   40.00         qled     1  19.2
147       samsung         1        0    4.30   43.00          led     1  25.6
148       toshiba         1        0    4.60   55.00          led     1  19.2
149       samsung         1        0    4.20   55.00          led     1  32.0
150         croma         1        0    4.20   55.00         qled     1  32.0
151            lg         1        0    4.65   55.00         oled     1  44.8
152            lg         1        0    4.55   55.00      miniled     1  22.4
153            vw         1        0    4.50   50.00         qled     1  32.0
154            lg         0        0    4.00   32.00          led     1  16.0
155            lg         1        0    4.20   50.00          led     1  19.2
156       samsung         1        0    4.20   55.00        micro     1  25.6
157            lg         1        0    4.05   55.00          led     1  19.2
158            lg         0        0    4.55   32.00          led     1  16.0
159            lg         0        0    4.45   32.00          led     1  16.0
160            lg         1        0    4.35   65.00      miniled     1  16.0
161      motorola         0        0    4.75   32.00         qled     1  16.0
162      motorola         1        0    4.70   55.00         qled     1  32.0
163        xiaomi         1        0    4.70   65.00      miniled     1  32.0
164      acerpure         1        0    4.70   42.52         qled     1  32.0
165        foxsky         0        1    4.50   40.00         qled     1  19.2
166        xiaomi         1        0    4.35   75.00         qled     1  32.0
167            lg         1        0    4.30   55.00      miniled     1  28.8
168        foxsky         1        0    4.10   43.00      miniled     0  22.4
169       philips         1        0    4.70   65.00      miniled     1  32.0
170            vw         1        0    4.65   43.00         qled     1  16.0
171       hisense         1        0    4.20   43.00         qled     1  16.0
172       hisense         1        0    4.75   75.00      miniled     1  35.2
173            vw         1        0    4.00   55.00         qled     1  16.0
174       thomson         1        0    4.55   55.00         qled     1  32.0
175       hisense         1        0    4.20   43.00         qled     1  16.0
176          acer         1        0    4.30   43.00          led     1  16.0
177      acerpure         1        0    4.25   75.00         qled     1  16.0
178     blaupunkt         1        0    4.10   43.00         qled     1  22.4
179      acerpure         1        0    4.60   55.00         qled     1  16.0
180     panasonic         0        0    4.10   32.00          led     1  16.0
181           tcl         0        1    4.70   50.00         qled     1  19.2
182        realme         1        0    4.05   55.00         qled     1  22.4
183            vu         1        0    4.75   50.00         qled     1  16.0
184        xiaomi         0        0    4.50   32.00          led     1  16.0
185           tcl         1        0    4.20   55.00      miniled     1  44.8
186       philips         1        0    4.25   50.00         qled     1  32.0
187           tcl         1        0    4.55   77.00      miniled     1  44.8
188        xiaomi         0        0    4.15   32.00         qled     1  16.0
189           tcl         1        0    4.65   65.00      miniled     1  19.2
190        coocaa         0        0    4.60   32.00         qled     1  16.0
191            lg         1        0    4.55   50.00          led     1  19.2
192           tcl         1        0    4.05   55.00      miniled     1  25.6
193       hisense         1        0    4.30   65.00         qled     1  25.6
194       hisense         1        0    4.30   75.00      miniled     1  44.8
195          sony         1        0    4.65   75.00          led     1  16.0
196       hisense         1        0    4.35   43.00         qled     1  28.8
197           tcl         1        0    4.40   43.00          led     1  16.0
198           tcl         1        0    4.75   65.00      miniled     1  16.0
199          sony         1        0    4.60   55.00          led     1  16.0
200      motorola         1        0    4.35   55.00         qled     1  32.0
201         haier         1        0    4.25   55.00      miniled     1  32.0
202      motorola         1        0    4.05   65.00         qled     1  32.0
203       samsung         1        0    4.05   43.00          led     1  19.2
204        xiaomi         1        0    4.40   43.00          led     1  32.0
205       samsung         1        0    4.40   65.00         oled     1  41.6
206       samsung         0        0    4.50   32.00          led     1  16.0
207       samsung         1        0    4.20   65.00      miniled     1  32.0
208        xiaomi         1        0    4.70   55.00          led     1  22.4
209       samsung         1        0    4.55   55.00         oled     1  38.4
210       samsung         1        0    4.60   65.00      miniled     1  35.2
211       hisense         1        0    4.55   55.00         qled     1  28.8
212           tcl         1        0    4.50   43.00          led     1  19.2
213      iffalcon         1        0    4.20   65.00          led     1  16.0
214           tcl         0        1    4.05   40.00         qled     1  19.2
215           tcl         1        0    4.70   55.00         qled     1  16.0
216      iffalcon         0        1    4.70   40.00          led     1  19.2
217       samsung         1        0    4.70   55.00         qled     1  19.2
218       samsung         1        0    4.20   43.00          led     1  19.2
219       samsung         1        0    4.60   43.00         qled     1  22.4
220         lumio         1        0    4.70   43.00         qled     1  16.0
221        xiaomi         1        0    4.25   65.00         qled     1  32.0
222           tcl         0        0    4.00   32.00         qled     1  16.0
223       thomson         0        0    4.30   32.00          led     1  16.0
224            lg         0        0    4.10   32.00          led     1  16.0
225       thomson         1        0    4.10   43.00         qled     1  22.4
226        foxsky         1        0    4.45   55.00         qled     1  16.0
227            vu         1        0    4.15   55.00         qled     1  16.0
228        foxsky         0        0    4.10   32.00         qled     1  16.0
229       infinix         1        0    4.25   43.00         qled     1  16.0
230          acer         1        0    4.75   43.00         qled     1  16.0
231        realme         1        0    4.15   65.00          led     1  16.0
232        realme         1        0    4.25   50.00         qled     1  16.0
233        realme         1        0    4.15   43.00          led     1  16.0
234          sony         1        0    4.60   55.00          led     1  16.0
235         haier         1        0    4.55   65.00         qled     1  32.0
236          sony         1        0    4.60   55.00      miniled     1  32.0
237         haier         1        0    4.35   43.00         qled     1  32.0
238      motorola         1        0    4.55   50.00      miniled     1  16.0
239       samsung         1        0    4.30   43.00          led     1  22.4
240            lg         1        0    4.10   55.00         oled     1  25.6
241       hisense         1        0    4.70   43.00         qled     1  16.0
242     panasonic         1        0    4.55   43.00          led     1  16.0
243        foxsky         0        1    4.40   32.00          led     1  19.2
244          marq         0        1    4.60   32.00          led     1  19.2
245            lg         1        0    4.55   43.00          led     1  28.8
246        xiaomi         1        0    4.40   50.00          led     1  16.0
247        xiaomi         1        0    4.15   43.00          led     1  16.0
248     blaupunkt         1        0    4.15   49.00          led     1  22.4
249       samsung         1        0    4.45   55.00         qled     1  32.0
250      ifflacon         1        0    4.45   65.00          led     1  19.2
251          akai         0        1    4.05   43.00          led     0  19.2
252      ifflacon         1        0    4.25   43.00          led     1  22.4
253         kodak         0        1    4.05   43.00         qled     1  19.2
254         kodak         0        0    4.35   32.00         qled     1  16.0

# Trying to Prediction

In [55]:
X.columns

Index(['brand', 'ultra_hd', 'full_hd', 'Rating', 'inches', 'display_type',
       'wifi', 'rom', 'value_score', 'smart_features', 'Company_amazon',
       'Company_croma', 'Company_flipkart', 'ppi', 'resolution_width',
       'resolution_height', 'fast_charging', 'ram', 'Spec_Score',
       'size_category', 'charging_category', 'brand_category'],
      dtype='object')

In [56]:
X.iloc[0].values

array(['tcl', 1, 0, 4.65, 55.0, 'qled', 1, 16.0, 0.0062722388892764, 4.0,
       0.0, 0.0, 1.0, 3.0, 1.0, 2.0, 1.0, 1.0, 3.0, 1.0, 2.0, 'big'],
      dtype=object)

In [57]:
pipeline.named_steps['preprocessing'].feature_names_in_

array(['brand', 'ultra_hd', 'full_hd', 'Rating', 'inches', 'display_type',
       'wifi', 'rom', 'value_score', 'smart_features', 'Company_amazon',
       'Company_croma', 'Company_flipkart', 'ppi', 'resolution_width',
       'resolution_height', 'fast_charging', 'ram', 'Spec_Score',
       'size_category', 'charging_category', 'brand_category'],
      dtype=object)

In [58]:
data = [['lg', 0, 0, 4.0, 55, 'led', 1, 1.0, 0, 4, 0, 0, 1, 3, 2, 1, 2, 1, 4, 1, 2, 'big']]

columns = ['brand', 'ultra_hd', 'full_hd', 'Rating', 'inches', 'display_type',
       'wifi', 'rom', 'value_score', 'smart_features', 'Company_amazon',
       'Company_croma', 'Company_flipkart', 'ppi', 'resolution_width',
       'resolution_height', 'fast_charging', 'ram', 'Spec_Score',
       'size_category', 'charging_category', 'brand_category']

one_df = pd.DataFrame(data, columns = X.columns)
one_df

,brand,ultra_hd,full_hd,Rating,inches,display_type,wifi,rom,value_score,smart_features,Company_amazon,Company_croma,Company_flipkart,ppi,resolution_width,resolution_height,fast_charging,ram,Spec_Score,size_category,charging_category,brand_category
0,lg,0,0,4.0,55,led,1,1.0,0,4,0,0,1,3,2,1,2,1,4,1,2,big

In [59]:
np.expm1(pipeline.predict(one_df))[0]

11.660442031193714